### ISSUE TITLE
Add option to change dependency direction between an Interface an the implementing classes

### ISSUE THREAD

**Issue by BenjaminWeisheit** [SAP2Moose/SAP2Moose#131]
Hello Rainer,

Currently the dependency arrow between an interface and a class that implements the interface always points from the interface towards the class. It would be really helpful to have an option that allows to switch this direction. So that a class points towards the interfaces it implements

At the same time a class that calls the methods/attributes defined in an interface should should also point toward the interface.

Example:
Implementing Class--->Implemented Interface<-----Client Class

Best regards,
Ben

**Comment by RainerWinkler** [comment]
Helo Benjamin,
thank you for the ticket. This helps a lot to organize the work :-)
I will implement it. I plan about a week for it. OK?
My idea is to add an additional check box as parameter. At a later time it might be replaced with a different and more flexible technique to configure the model determination.
Best Regards,
Rainer

**Comment by BenjaminWeisheit** [comment]
Hello Rainer, 

sounds great :-)

Best regards,
Ben

**Comment by RainerWinkler** [comment]
Hi @BenjaminWeisheit,
I added now the option to reverse the arrows. The arrows point now from the implementing method to the interface method.
Please test.
Best Regards,
Rainer

**Comment by BenjaminWeisheit** [comment]
Hi @RainerWinkler,

thank you very much for the new feature. Switching the arrow direction works, and helps to check if the architecture has been violated. 

I found one strange behaviour when I tried to display a model with packages, classes and attributes. This causes an Exception in the Moose Panel (brand new image, installed yesterday): 
<img width="762" alt="Pharo_pBc8kdF1xM" src="https://user-images.githubusercontent.com/77887261/107111051-0b857c00-684d-11eb-90a1-cc4f058ab79c.png"> 

On the other hand, displaying the model without attributes (only packages or only packages and classes) works. Is this caused by the latest changes to the extractor? Or is this just a handling issue?

You mentioned that you are currently working on a meta model and I think i have another feature request. Would  it possible to display accesses to attributes as blue arrows, instead of blue lines? This would be helpful to check if dependency inversion has been respected for attributes, too.

Thank you and best regards,
Ben

**Comment by RainerWinkler** [comment]
Hi @BenjaminWeisheit,

Did you restrict the amount of elements to be displayed or do you try to display all elements? When I try to display all elements, the pop up with a warning message is raised earlier in the call hierarchy:

![image](https://user-images.githubusercontent.com/16272077/107151905-6dd1a000-6965-11eb-9372-8689284e0eba.png)

Anyhow, please open a ticket in Moose2Mode for this.

Best Regards,
Rainer

PS: I might need an instruction how to reproduce or an image with the error to analyze this

**Comment by RainerWinkler** [comment]
Hi @BenjaminWeisheit,
regarding the blue arrow to attributes.
You can find the metamodel I spoke of in this preprint: http://dx.doi.org/10.13140/RG.2.2.13306.41927
In this paper I speak about visualizing read and write access with arrows. Technically this is not yet done, because 1. the used FAMIX model cannot store such an information well and 2. It makes extraction in SAP2Moose more complex (Currently only the where-used tables of SAP are analyzed, to see if a read or write access is done, the code has to be analyzed).

But probably my understanding of dependencies as it is written in the paper is to simple. There may be two kinds of dependencies: 1. Data Flow. 2 Typing. I focused on the first, so I pointed the arrows for interface method the way I did, you needed the second, so you asked me to reverse it.

Regarding the blue line to attributes. I guess it is possible to make a change to Moose2Model that the access is visualized by a blue line with an arrow which points always to the attribute. You may open a ticket for this in the Moose2Model project when you need this. I think it can be implemented.

Best Regards,
Rainer

**Comment by BenjaminWeisheit** [comment]
Hi @RainerWinkler, 

sorry for the late reply. This week has been quite busy. 

You're right, I'm particularly interested in the way how objects are coupled. The direction of the arrows would help me to spot violations of our architecture (e.g. circular dependencies) more easily. 

I will open the tickets in Moose2Model.

Thanks again for the great work and especially the super quick implementation of the switched interface arrow direction.

Best regards,
Ben
